### ISSUE TITLE
Android: addOrientationListener gets triggered infinite times

### ISSUE THREAD

**Issue by bharath-kamath** [wonday/react-native-orientation-locker#1]
The `addOrientationListener` keeps getting triggered many times irrespective of if the device changed its orientation or not. Holding the device in portrait, will trigger this listener many times.

Also, this does not get triggered when we do a `lockToPortrait()`.

Tried it on RN 0.39.2 and 0.44

**Comment by wonday** [comment]
I had filtered the event when the same event coming, and only send one. 
please use version 1.0.2 to test it again.

>this does not get triggered when we do a lockToPortrait().
If before calling lockToPortrait(), the orientation is PORTRAIT, it will not trigger the event.
If it is LANDSCAPE-LEFT/RIGHT, it will trigger a event.
I test it on RN 0.43.0 and android 5.1.1(phone) and android 7.0 in simulator.

**Comment by bharath-kamath** [comment]
Are you saying the below scenario will not be triggered ?

Phone is is portrait, I have called `lockToPortrait()`. But when the device is rotated, i need to know that phone has changed orientation. And later when it is rotated back to portrait, need an event to fire again.

**Comment by wonday** [comment]
Yes, when phone is portrait and call locktoPortrait(),  it will not be fired again even you rotate the phone.
It will be fired when unlockAllOrientations() was called if the phone real orientation is not portrait. 
If when phone is portrait and call lockToLandscapeLeft, it will fire a event.

You should only relayout your view in addOrientationListener's callback.

I think you should:
1. get initial orientation and layout as it.
2. listening the event and relayout it.
3. as your need to lockToXXX();

**Comment by bharath-kamath** [comment]
So basically my use case is that my screen is locked to potrait, as in there is no landscape view. But when the phone is rotated, I Push a new controller. Hence, even if I lockToXX, I would still want listeners to fire.

I will fork it and try to and a `lockToXXContinueListenting()` function.

**Comment by bharath-kamath** [comment]
`1.0.2` fixes the infinite listener call.
