### ISSUE TITLE
lockToPortrait on Ios

### ISSUE THREAD

**Issue by diegotsi** [wonday/react-native-orientation-locker#10]
I'm having this exception when i use lockToPortrait on ios

```Application threw exception NSInternalInconsistencyException: Could not locate shadow view with tag #472 Originated at or in a subcall of __32-[RCTUIManager setSize:forView:]_block_invoke```

**Comment by wonday** [comment]
Anybody know what cause this?

**Comment by diegotsi** [comment]
I dont know exactly but i put a setTimeout after a certain action and before lockToPortrait and it works.
