### ISSUE TITLE
react-native 0.60 autolinking

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [wonday/react-native-orientation-locker#102]
the readme is confusing and there is no clear installation instructions

there is no instructions on support for react native 0.60 autolinking feature

https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by billygl** [comment]
It works without autolinking for iOS and it is autolinking the android part. (You should avoid "Add following to MainApplication.java (This will be added automatically by the react-native-link. If not, please manually add the following )" part)
For android, the readme is ok.
For iOS, you should use 
`pod install`
after adding the line explained in the "Using CocoaPods (iOS Only)" section.

**Comment by pcguru** [comment]
react-native-link will be deprecated in React-Native 0.62. The readme is still a bit confusing for Android? Will the code after "This will be added automatically by the react-native-link" need to be added manually in react-native 0.62?

**Comment by wonday** [comment]
@pcguru 
Thank you, I have modified the readme.
