### ISSUE TITLE
Cannot read property 'UNKNOWN' of undefined

### ISSUE THREAD

**Issue by olafurnsig** [wonday/react-native-orientation-locker#109]
Using Typescript in our project, so we're importing the OrientationType from the library, import is like this:

`import Orientation, { OrientationType } from 'react-native-orientation-locker';`

```
type BottomBarState = {
  orientation: OrientationType;
};

class BottomBar extends React.Component<TabBarBottomProps, BottomBarState> {
  constructor(props: TabBarBottomProps) {
    super(props);

    this.state = {
      orientation: OrientationType.UNKNOWN,
    };
  }
.............
}
```

This throws an undefined error, same with any other item in the enum.

All the orientation listeners work fine, just the OrientationType import that somehow is undefined, even tough it is here in the react-native-orientation-locker/index.d.ts : 

`export enum OrientationType {
  PORTRAIT = "PORTRAIT",
  PORTRAIT_UPSIDEDOWN = "PORTRAIT-UPSIDEDOWN",
  LANDSCAPE_LEFT = "LANDSCAPE-LEFT",
  LANDSCAPE_RIGHT = "LANDSCAPE-RIGHT",
  UNKNOWN = "UNKNOWN"
}`

**Comment by olafurnsig** [comment]
And according to the readme these are the possible Orientation types:

orientation can return one of:

- PORTRAIT
- LANDSCAPE-LEFT 
- LANDSCAPE-RIGHT 
- PORTRAIT-UPSIDEDOWN
- FACE-UP
- FACE-DOWN
- UNKNOWN

So FACE-UP and FACE-DOWN are missing from the OrientationType enum in the typings

**Comment by wonday** [comment]
added it to v1.1.8

**Comment by olafurnsig** [comment]
Alright - What about the issue of OrientationType enum being undefined, possibly at app start?

**Comment by wonday** [comment]
If you still cause OrientationType enum undefined, maybe you can use hard coding 
```
orientation: "UNKNOWN"
```
I do not know why...

**Comment by olafurnsig** [comment]
OrientationType in 1.18 resolves this
