### ISSUE TITLE
native module cannot be null

### ISSUE THREAD

**Issue by tallyinteractive** [wonday/react-native-orientation-locker#12]
After importing 'react-native-orientation-locker', I get this error: native module cannot be null. Anyone else have this problem?

**Comment by wonday** [comment]
Have you run ```react-native link react-native-orientation-locker```？
or it is failed, android or iOS? you can add it manually as other lib.

**Comment by emilany** [comment]
Also encountering this error. Ran `react-native link react-native-orientation-locker` as well. Possible workaround?
