### ISSUE TITLE
On iPad, iOS 11, everything working great if don't select Portrait Upside Down. But...

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [wonday/react-native-orientation-locker#13]
On iPad, iOS 11, everything working great if don't select Portrait Upside Down. If select, then the locking doesn't seem to work. The problem is for Multitasking mode to work on iPad apps, Apple requires Portrait Upside Down to be checked.

**Comment by wonday** [comment]
Yes, it does not support Portrait Upside Down.
