### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by yudhaaw96** [wonday/react-native-orientation-locker#137]
"react-native-orientation-locker": "^1.2.0",

info Installing the app...
> Task :app:generateDebugBuildConfig FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 2 executed

**Comment by canberkardic** [comment]
Same problem here
