### ISSUE TITLE
Jest test fails!

### ISSUE THREAD

**Issue by rimzici** [wonday/react-native-orientation-locker#14]
All seem to work fine for me, except the test fails. After installing and Linking the module, jest throws error.

```
 Invariant Violation: Native module cannot be null.
```

from the log:
```
at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at new NativeEventEmitter (node_modules/react-native/Libraries/EventEmitter/NativeEventEmitter.js:29:7)
      at Object.<anonymous> (node_modules/react-native-orientation-locker/index.js:23:25)
```

Need help please.
Thanks!

**Comment by wonday** [comment]
react-native link failed? 
Check manually.

**Comment by rimzici** [comment]
Yes, in fact the automatic link did fail.

I tried the manual steps in [here](https://github.com/yamill/react-native-orientation),
replacing `react-native-orientation` with `react-native-orientation-locker`. And both android and ios builds seem to work fine, only the jest throws error!

Could it still be the issue in linking ?

**Comment by rimzici** [comment]
Okay. Thanks, Let me try.
There is one more thing that came into my notice. Not sure if that is the expected behaviour or not, hope I can mention that in here, it is not related to this issue.

On doing 
`Orientation.lockToLandscapeLeft();` 
the orientation listener
```
Orientation.addOrientationListener((orientation: string) => {
// GIVES orientation='LANDSCAPE-RIGHT'
});
```
and vice-versa, Is it supposed to be that way? :)
Thanks!

**Comment by rimzici** [comment]
Thanks!

**Comment by wonday** [comment]
released v1.0.13

**Comment by rimzici** [comment]
Wonderful 😃
I will try. Thanks Man!

**Comment by rimzici** [comment]
BTW I have fixed the jest issue as you suggested, by mocking the module
```
jest.mock('react-native-orientation-locker', () => {
	return {
		addEventListener: jest.fn(),
		removeEventListener: jest.fn(),
		lockToPortrait: jest.fn(),
		lockToLandscapeLeft: jest.fn(),
		lockToLandscapeRight: jest.fn(),
		unlockAllOrientations: jest.fn(),
	};
});
```

**Comment by lfoliveir4** [comment]
> BTW I have fixed the jest issue as you suggested, by mocking the module
> 
> ```
> jest.mock('react-native-orientation-locker', () => {
> 	return {
> 		addEventListener: jest.fn(),
> 		removeEventListener: jest.fn(),
> 		lockToPortrait: jest.fn(),
> 		lockToLandscapeLeft: jest.fn(),
> 		lockToLandscapeRight: jest.fn(),
> 		unlockAllOrientations: jest.fn(),
> 	};
> });
> ```

This solved for me

**Comment by ws7one** [comment]
I am getting 
`TypeError: _reactNativeOrientationLocker.default.lockToPortrait is not a function`
even after mocking it as mentioned above.

**Comment by callmemonky** [comment]
> BTW I have fixed the jest issue as you suggested, by mocking the module
> 
> ```
> jest.mock('react-native-orientation-locker', () => {
> 	return {
> 		addEventListener: jest.fn(),
> 		removeEventListener: jest.fn(),
> 		lockToPortrait: jest.fn(),
> 		lockToLandscapeLeft: jest.fn(),
> 		lockToLandscapeRight: jest.fn(),
> 		unlockAllOrientations: jest.fn(),
> 	};
> });
> ```

This solved for me as well.

**Comment by callmemonky** [comment]
> I am getting `TypeError: _reactNativeOrientationLocker.default.lockToPortrait is not a function` even after mocking it as mentioned above.

Can you share your code, maybe people can debug that.

**Comment by callmemonky** [comment]
```
const mockLockToLandscapeLeft = jest.fn();
const mockUnlockAllOrientations = jest.fn();

jest.mock('react-native-orientation-locker', () => {
  return {
    lockToLandscapeLeft: () => mockLockToLandscapeLeft,
    unlockAllOrientations: () => mockUnlockAllOrientations,
  };
});
```

Working code. @ws7one
