### ISSUE TITLE
Does not work at all on iOS 14

### ISSUE THREAD

**Issue by bockc** [wonday/react-native-orientation-locker#146]
Hello,

We've been using your package for quite some time now and we recently noticed that with the iOS 14 update, almost all of the features of this library are broken and don't work anymore. We tried upgrading to 1.2.0 with no success, it still does not work.

**lockToXXX():** when called, the device rotates in the desired position but instantly rotates back to portrait right after.
**unlockAllOrientations:** when called, nothing changes, the device still can't rotate at all

It works fine on Android 10 as far as we've tested in our use cases. We didn't change any code about this recently, so I'm lead to think this library needs an update to support iOS 14.

Would you have any idea as to what could cause such a behaviour with your package ?

EDIT: I can confirm that this works flawlessly in 1.2.0 on iOS 13, so there's definitely an issue with iOS 14 devices. I also tried the version on the master branch but with no success either.

**Comment by bockc** [comment]
I figured something out : after upgrading my react-native version and many other dependencies, the behaviour of this package's listeners changed. Before upgrading, the listeners kept working wether my video-player was in fullscreen or not. Now, the listeners don't work anymore when switching modes.

I fixed my issue by adding an orientation change listener when I'm first displaying the video-player and another every time the players goes in fullscreen, I add another listener especially for the fullscreen mode that I remove once the player leaves fullscreen. It works this way but it doesn't really explain all the issues I encountered, so maybe my assumptions were wrong or I missed something somewhere.

I'm leaving this issue open for now in case you'd like to dig in a little bit, but feel free to close it if you prefer.

**Comment by mikehuebner** [comment]
Having a similar problem, I'm working on a fix for it and I think it has something to do with this.

```
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(nullable UIWindow *)window {
  return [OrientationManager getOrientation];
}
```

Removing this prevents the screen from rotating and locking it does nothing. I think there is an update in iOS 14. I'm looking for an answer now.

**Comment by bockc** [comment]
I'm also noticing a strange behaviour :
**Android**: the first time I call ```lockToLandscape()```, the view rotates to landscape and instantly back to portrait. This only occurs once, the first time, and after that no matter how many times I switch to landscape/portrait, everything works fine. Error on my side or bug ?

**Comment by bendadaniel** [comment]
I have same problem like a @bockc 

`lockToXXX(): when called, the device rotates in the desired position but instantly rotates back to portrait right after.`

IOS: 14.0.1
RN: 0.63.3
Locker package: 1.2.0

Do you have any solution?

**Comment by bockc** [comment]
We completely rewrote our video player using expo's video player and now it seems to work fine. Maybe this was a conflict with another package also making calls to manage screen orientation, anyway I'm sorry but we have no clue how to actually fix it...
I'm closing this issue since I found a 'solution' for my use case

**Comment by mikehuebner** [comment]
I haven't had any time to actually work on a fix for this, ended up trying to fork this and dig into it but other things took priority over this. When I get time I'll see if I can't find a fix. I'm going to check out expo's video player in the meantime... 👀

**Comment by castalonirenz** [comment]
this is working fine previously but when i updated to latest IOS 14 when i try to manually set the orientation to landscape it automatically follow the device physical orientation

**Comment by castalonirenz** [comment]
> I'm also noticing a strange behaviour :
> **Android**: the first time I call `lockToLandscape()`, the view rotates to landscape and instantly back to portrait. This only occurs once, the first time, and after that no matter how many times I switch to landscape/portrait, everything works fine. Error on my side or bug ?

same here

**Comment by davidcort** [comment]
Same issue, not works in iPad device :(

**Comment by kidasov** [comment]
Same issue. Any help will he be highly appreciated. When I lock orientation to landscape, device orientation changes for a moment but then it rotates back to portrait.
