### ISSUE TITLE
No visible @interface for 'Orientation' declares the selector 'addOrientationListener:' and 'removeListeners'

### ISSUE THREAD

**Issue by tolgaduzenli** [wonday/react-native-orientation-locker#15]
Orientation.m 

- (instancetype)init
{
    if ((self = [super init])) {
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(deviceOrientationDidChange:) name:@"UIDeviceOrientationDidChangeNotification" object:nil];
        [self addListener:@"orientationDidChange"];
    }
    return self;
}

- (void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self];
    [self removeListeners:1];
}

**Comment by wonday** [comment]
build error?
Your Xcode and SDK version?
I use Xcode 9.4 and SDK 11.4, it is OK.

**Comment by tolgaduzenli** [comment]
xcode: Version 9.3 (9E145)
sdk: 10.3.1
error:
No visible @interface for 'Orientation' declares the selector 'addListener:'

**Comment by wonday** [comment]
addListener/removeListeners was defined at RN RCTEventemitter (Orientation extends from it),
What is your RN version?
You can use v1.0.13, 
v1.0.14 just add this for remove warning

**Comment by indapublic** [comment]
Same situation.
XCode 9.2
"react-native": "0.42.3" (unfortunetaly, cannot upgrade at the moment)
