### ISSUE TITLE
Screen is fluctuating between portrait and landscape.

### ISSUE THREAD

**Issue by muneeb-techknit** [wonday/react-native-orientation-locker#165]
I have locked the orientation to portrait in my App component for the whole app and trying to unlock orientation on a specific screen. Below is the code locking orientation in my App Component.

` const _onOrientationDidChange = (orientation) => {
    if (
      orientation === "PORTRAIT" ||
      orientation === "LANDSCAPE-LEFT" ||
      orientation === "LANDSCAPE-RIGHT"
    ) {
      Orientation.lockToPortrait();
    }
  };

  useEffect(() => {
    Orientation.lockToPortrait();
    Orientation.addOrientationListener(_onOrientationDidChange);
  }); `

Below code is in the screen where both portrait and landscape are required.

` const _onOrientationDidChange = (orientation) => {
    console.log('orientation =', orientation);
    Orientation.unlockAllOrientations();
  };

useEffect(() => {
    Orientation.unlockAllOrientations();
    Orientation.addOrientationListener(_onOrientationDidChange);
    return () => {
      Orientation.removeOrientationListener(_onOrientationDidChange);
      Orientation.lockToPortrait();
    }
},[]); `

but the addOrientationListener callback is continuously calling and my screen is fluctuating between portrait and landscape while my device orientation is fixed to the landscape. The issue is for both (IOS and Android).
One more thing, If I don't call addOrientationListener, the screen rotation is not working at all. It seems like unlockAllOrientations is not working if the listener is not called.

**Comment by Juliocbr** [comment]
@muneeb-techknit  did you manage to resolve this issue?, I have the same problem

**Comment by aniket-dalvi** [comment]
check out the InteractionManager module of react-native and try to integrate the same using InteractionManager.

**Comment by aniket-dalvi** [comment]
Did you guys find any solution? I am also facing the same issue.
