### ISSUE TITLE
[feature request] get orientation for app and device

### ISSUE THREAD

**Issue by mxmzb** [wonday/react-native-orientation-locker#17]
there is a difference between app orientation and device orientation, e.g. you may lock an app to a specific orientation (portrait) and later you want to know the device orentation (which may change to landscape) without unlocking the app orientation itself.

**Comment by wonday** [comment]
I have added this at v1.0.21

**Comment by mxmzb** [comment]
that's absolutely terrific, thank you so much!! 👍
