### ISSUE TITLE
Is README.md outdated?

### ISSUE THREAD

**Issue by Vitor-Felix** [wonday/react-native-orientation-locker#177]
I was trying to do the step-by-step process reading `README.md`.

But I couldn't use `<OrientationLocker>` as suggested in this [part of the guide](https://github.com/wonday/react-native-orientation-locker#reactive-component-orientationlocker). Instead I used `<ScreenOrientation>` as suggested in the description of the package on `npmjs` site. [link here](https://www.npmjs.com/package/react-native-orientation-locker#reactive-component-screenorientation).

Both components are current? Is one documentation most current than the other one?

So as you can see, this isn't really an issue, but a kind of a question. Sorry for asking here, but i didn't knew where to ask.

**Comment by FuzzyAtish** [comment]
With the latest release `1.3.0` this seems to have been resolved.
In other words, I had to use `<OrientationLocker>` instead of `<ScreenOrientation>`

**Comment by alburdette619** [comment]
I am on 1.3.0 and am seeing this as well.  `OrientationLocker` is exported only as a type.  It really seems nothing from `./src/OrientationListener` is being exported despite the export statement in `index.js`.  The hooks seem to be exported fine.

<img width="523" alt="Screen Shot 2021-05-19 at 5 56 22 PM" src="https://user-images.githubusercontent.com/22638838/118890234-55f6aa00-b8cc-11eb-90bd-0080e4816c16.png">
<img width="803" alt="Screen Shot 2021-05-19 at 5 56 37 PM" src="https://user-images.githubusercontent.com/22638838/118890238-568f4080-b8cc-11eb-9811-62ce3da93c93.png">

**Comment by Vitor-Felix** [comment]
Well it seems that both the component usage as the documentation, where updated (2 days ago on npmjs). So I think that resolve my issue. Thank you guys!
