### ISSUE TITLE
Calling UI code from background thread (iOS)

### ISSUE THREAD

**Issue by thedjinn** [wonday/react-native-orientation-locker#18]
Hi, Xcode emits runtime issues inside the native `getOrientation` method. The problem is that `[UIApplication statusBarOrientation]` is UI code, which may only be called from the main thread.

Since this function is already asynchronous (by having a callback), the solution would be to wrap the `UIApplication` call inside a GCD or NSOperationQueue async block and subsequently call the callback from the originating queue.

**Comment by wonday** [comment]
I have commit a fixed version, can you see main branch codes fix it or not?
