### ISSUE TITLE
[Question] Install with swift

### ISSUE THREAD

**Issue by Queeniie** [wonday/react-native-orientation-locker#182]
Hello,

I'm trying to install this package for my app but my AppDelegate is a swift file, and I have no idea how to translate the code snippet in the README to swift.

Can someone help me please? It would be greatly appreciated.
Thanks!

**Comment by Queeniie** [comment]
For anyone who needs swift as well, here's how to do it:

- Add `#import "Orientation.h"` to your bridging-header file.
- Add to your `AppDelegate.swift`
```
func supportedInterfaceOrientations(for window: UIWindow?) -> UIInterfaceOrientationMask {
      return Orientation.getOrientation()
  }
```

 :)

**Comment by Queeniie** [comment]
I'm not sure if it's related to the way I initialized the library or if I missed something but i do have the same problem as #146 , where my view rotates for a split second to landscape before going back to portrait (when I want it to stay in landscape mode). 
I also tried to lock the orientation for Portrait to my other screens but the view still follows the orientation of the device.  :/

**Comment by thomasboel** [comment]
I am also having the exact same issue as @Queeniie 
Device rotates to landscape if I call lockToLandscape() but goes straight back to portrait if I am holding the device in portrait.
I have added the function to AppDelegate.swift (and AppDelegate.m, not sure why the .m and .h files are still present in my project, but that's besides the point)

**Comment by HeavenMin** [comment]
it should be 
```swift
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        return Orientation.getOrientation()
    }
    ```

**Comment by markrickert** [comment]
I had to add `override ` to get xcode to compile:

```swift
override func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
  return Orientation.getOrientation()
}
```
