### ISSUE TITLE
Android does not lock

### ISSUE THREAD

**Issue by alburdette619** [wonday/react-native-orientation-locker#183]
Library Version: `1.3.1`
RN Version: `0.64.0`
Android Version: `11`

We don't seem to have updated this library or the code around it recently though I did try upgrading to the latest as you can see and the issue persisted.

**Description**
On Android, calling one of the `lockTo...` functions doesn't seem to work at all suddenly.  I have followed the setup carefully as seen below.  The hook is called to set the lock once, makes it through the tablet condition, and does not throw an error, but the screen on Android will rotate no matter what.

`AndroidManifest.xml`
<img width="776" alt="Screen Shot 2021-05-19 at 6 47 23 PM" src="https://user-images.githubusercontent.com/22638838/118894647-a7a23300-b8d2-11eb-8a73-4eb228d778ed.png">
`MainActivity.java`
<img width="950" alt="Screen Shot 2021-05-19 at 6 47 39 PM" src="https://user-images.githubusercontent.com/22638838/118894864-0ebfe780-b8d3-11eb-8ecf-64d6806f4486.png">
`MainApplication.java`
<img width="609" alt="Screen Shot 2021-05-19 at 6 47 59 PM" src="https://user-images.githubusercontent.com/22638838/118894865-0ebfe780-b8d3-11eb-802d-a6efdf823415.png">
`App.tsx`
<img width="423" alt="Screen Shot 2021-05-19 at 6 49 27 PM" src="https://user-images.githubusercontent.com/22638838/118894867-0ebfe780-b8d3-11eb-93a2-61a446e5cf23.png">

**Comment by alburdette619** [comment]
I have tried moving the order of the call in `onCreate` to the end and it didn't work.  I've seen call order matter in this instance, but not here.

**Comment by alburdette619** [comment]
Closing as I cannot repro this on a new app with only your library installed.  Something here is happening here to obscure the activity or something because even debugging the native code I saw the activity was present and `isLocked` was set to true.

**Comment by alburdette619** [comment]
Anyone looking in the future, it was a bug on `react-native-screens` setting it to `unspecified`.  The new version should be out soon after this post I hope.  At the moment I am having to use master or patch

**Comment by linhvovan29546** [comment]
> Anyone looking in the future, it was a bug on `react-native-screens` setting it to `unspecified`. The new version should be out soon after this post I hope. At the moment I am having to use master or patch

hi @alburdette619 Can you tell me how to solve it?

**Comment by matinzd** [comment]
> Anyone looking in the future, it was a bug on `react-native-screens` setting it to `unspecified`. The new version should be out soon after this post I hope. At the moment I am having to use master or patch

Oh god! I have been dealing with this whole time. I thought that there was a bug in my code and I am unlocking orientation somwhere. I also tried locking orientation in main activity but it didn't work. Just upgraded `react-native-screens` from 3.0.0 to 3.12.0 and it's fixed now. Damn ....
