### ISSUE TITLE
[Android] undefined is not an object

### ISSUE THREAD

**Issue by flaviotobi** [wonday/react-native-orientation-locker#2]
Hi there, i'm having a issue in Android.
When i try to do any function like `Orientation.lockToPortrait() ` i keep getting  this same error :
![3202688983276820592-account_id 1](https://user-images.githubusercontent.com/13239857/27141407-f8912e70-511f-11e7-83ac-5091eeedcbe6.png)

The stranger thing is when i do a `console.log(Orientation)`  i get this:
```
{ [Function: Orientation]
getOrientation: [Function],
lockToPortrait: [Function],
lockToPortraitUpsideDown: [Function],
 lockToLandscapeRight: [Function],
lockToLandscapeLeft: [Function],
unlockAllOrientations: [Function],
 addOrientationListener: [Function],
removeOrientationListener: [Function],
getInitialOrientation: [Function] }
```
From what i understand this is the correct result from the console.log, thats why i'm writing here, i just can't figure out the problem. 
PS: keep in mind that his bug is in android only, iOS works like a charm :)

**Comment by wonday** [comment]
Hi

maybe you forgot to execute "react-native link react-native-orientation-locker",
check you java file "MainApplication.java"
should be
```
import org.wonday.orientation.OrientationPackage;

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          ...
          new OrientationPackage(),
          ...
      );
    }
  };

```

**Comment by flaviotobi** [comment]
Thanks it works, for some reason i didn't had that added  :)

**Comment by Albert0405** [comment]
Hi, sometimes `react-native link` will not change the code in `MainApplication.java`

Please update your installation
