### ISSUE TITLE
addOrientationListener returns wrong orientation

### ISSUE THREAD

**Issue by SudoPlz** [wonday/react-native-orientation-locker#23]
Not sure why this happens, but the listeners passed to `addOrientationListener` return the previous orientation from what it actually is.

For example if I turn my device from portrait to landscape-left, the `orientation` value will be portrait.

As a result I know have to do:

```
Orientation.addOrientationListener((/* wrongOrientation */) => {
    Orientation.getOrientation((orientation) => {
      store.dispatch(setOrientation(orientation));
    });
  });
```

Has anyone faced that?

react-native: 0.56
environment: iOS Simulator iPhone XR
Xcode 10
"react-native-orientation-locker": "^1.0.18",

**Comment by Fsarmento** [comment]
I having the same issue. 

`addOrientationListener` has to params: `orientation` and `deviceOrientation`. `orientation` seems to be returning the previews orientation, while `deviceOrientation` is returning the correct orientation.

Btw, `getOrientation` also have the same two params (`orientation` and `deviceOrientation`). I am getting the correct orientation on `orientation` and `deviceOrientation` is alwais `undefined`.

**Comment by wonday** [comment]
orientation is the UI orientation, if you locked, it will not changed when rotating device.
deviceOrientation is the real device orientation, if you locked, it still can return current orientation of device.
You said ```deviceOrientation is alwais undefined```, 
can you tell me which platform happened?  android or iOS?

**Comment by Fsarmento** [comment]
I guess it is expected to be undefined... I was misled by the example in the README.md file:

 ```
   //get current orientation
    /*
    Orientation.getOrientation((orientation,deviceOrientation)=> {
      console.log("Current UI Orientation: ", orientation);
      console.log("Current Device Orientation: ", deviceOrientation);
    });
    */

```

However, a few lines below the definition of the `getOrientation` method shows that the callback only have one parameter. To get the device orientation there is the `getDeviceOrientation`.

```
getOrientation(function(orientation))
getDeviceOrientation(function(orientation))
```

Everything works as you explained  👍

**Comment by wonday** [comment]
@Fsarmento 
thank you, I have fixed sample codes.
