### ISSUE TITLE
`react-native-windows` peer dependency should be optional

### ISSUE THREAD

**Issue by jb-berthet** [wonday/react-native-orientation-locker#237]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🔥 

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-orientation-locker@1.5.0` for the project I'm working on.

I was not able to install your library on my project because it is requiring `react-native-windows` as a peer dependency (which I don't want to install on my React Native project).

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-orientation-locker/package.json b/node_modules/react-native-orientation-locker/package.json
index 68ddd27..a7a04b3 100644
--- a/node_modules/react-native-orientation-locker/package.json
+++ b/node_modules/react-native-orientation-locker/package.json
@@ -33,6 +33,11 @@
         "react-native": ">=0.63.2",
         "react-native-windows": ">=0.63.3"
     },
+    "peerDependenciesMeta": {
+        "react-native-windows": {
+            "optional": true
+        }
+    },
     "devDependencies": {
         "react": "16.13.1",
         "react-native": "0.63.2",
```

I will make a Pull Request for this change and I would appreciate you approve it! 🙂

**Comment by salorsino** [comment]
> Hi! 👋
> 
> Firstly, thanks for your work on this project! 🔥
> 
> Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-orientation-locker@1.5.0` for the project I'm working on.
> 
> I was not able to install your library on my project because it is requiring `react-native-windows` as a peer dependency (which I don't want to install on my React Native project).
> 
> Here is the diff that solved my problem:
> 
> ```diff
> diff --git a/node_modules/react-native-orientation-locker/package.json b/node_modules/react-native-orientation-locker/package.json
> index 68ddd27..a7a04b3 100644
> --- a/node_modules/react-native-orientation-locker/package.json
> +++ b/node_modules/react-native-orientation-locker/package.json
> @@ -33,6 +33,11 @@
>          "react-native": ">=0.63.2",
>          "react-native-windows": ">=0.63.3"
>      },
> +    "peerDependenciesMeta": {
> +        "react-native-windows": {
> +            "optional": true
> +        }
> +    },
>      "devDependencies": {
>          "react": "16.13.1",
>          "react-native": "0.63.2",
> ```
> 
> I will make a Pull Request for this change and I would appreciate you approve it! 🙂


In my project `npm install` just fails when this library is in my `package.json`. How were you able to nom install in the first place?

**Comment by eisodev** [comment]
This optional tag doesn't work at all:

```
npm install react-native-orientation-locker@1.5.0                                                                                                                                        

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myappnameedited
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!   peer react@">=16.13.1" from react-native-orientation-locker@1.5.0
npm ERR!   node_modules/react-native-orientation-locker
npm ERR!     react-native-orientation-locker@"1.5.0" from the root project
npm ERR!   1 more (react-native)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"18.2.0" from react-native-windows@0.72.9
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.63.3" from react-native-orientation-locker@1.5.0
npm ERR!   node_modules/react-native-orientation-locker
npm ERR!     react-native-orientation-locker@"1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/eisodev/.npm/_logs/2023-09-21T11_39_46_515Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/eisodev/.npm/_logs/2023-09-21T11_39_46_515Z-debug-0.log
```

**Comment by NiharR27** [comment]
Same issue:
```
npm ERR! Found: react-native@0.71.8
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.71.8" from the root project
npm ERR!   peer react-native@">=0.63.2" from react-native-orientation-locker@1.5.0
npm ERR!   node_modules/react-native-orientation-locker
npm ERR!     react-native-orientation-locker@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.72.3" from react-native-windows@0.72.14
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@">=0.63.3" from react-native-orientation-locker@1.5.0
npm ERR!   node_modules/react-native-orientation-locker
npm ERR!     react-native-orientation-locker@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```
