### ISSUE TITLE
App was rejected on Huawei AppGallery

### ISSUE THREAD

**Issue by XT-0515** [wonday/react-native-orientation-locker#246]
Huawei detected that our app got the accelerometer during initialization.

尊敬的开发者，您好！您的应用在用户同意隐私政策前存在获取用户个人信息（加速度传感器）的违规调用行为，请您将相关问题反馈至贵司的开发人员，自检日志及调用栈信息（不限于SDK的获取信息行为），应用上架需确保在用户同意隐私政策后再进行接口调用和个人信息获取。相关调用栈如下，请查收，谢谢！android.hardware.SensorManager.registerListener(SensorManager.java:823),
android.hardware.SensorManager.registerListener(SensorManager.java:730),
android.view.OrientationEventListener.enable(OrientationEventListener.java:105),
org.wonday.orientation.OrientationModule.<init>(OrientationModule.java:109),
org.wonday.orientation.OrientationPackage.createNativeModules(OrientationPackage.java:28),
com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42),
com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42),
com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462),
com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433),
com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327),
com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)

**Comment by huangnan78100** [comment]
I have the same problem

**Comment by huangnan78100** [comment]
App was rejected on xiaomi AppGallery

**Comment by huangnan78100** [comment]
什么时候能解决啊，现在小米应用市场上不了

**Comment by XT-0515** [comment]
> 什么时候能解决啊，现在小米应用市场上不了

这个是安卓代码初始化问题

**Comment by huangnan78100** [comment]
是初始化的问题，初始化module的时候，你有什么解决办法吗？

**Comment by huangnan78100** [comment]
> > 什么时候能解决啊，现在小米应用市场上不了
> 
> 这个是安卓代码初始化问题

我看了一下，不太好处理，你有什么解决办法吗？

**Comment by huangnan78100** [comment]
> > > 什么时候能解决啊，现在小米应用市场上不了
> > 
> > 
> > 这个是安卓代码初始化问题
> 
> 我看了一下，不太好处理，你有什么解决办法吗？

你们也是应用市场上不去？ 还是用什么规避方案先上市场

**Comment by XT-0515** [comment]
> > > 什么时候能解决啊，现在小米应用市场上不了
> > 
> > 
> > 这个是安卓代码初始化问题
> 
> 我看了一下，不太好处理，你有什么解决办法吗？

需要安卓工程师来改

**Comment by XT-0515** [comment]
> > > > 什么时候能解决啊，现在小米应用市场上不了
> > > 
> > > 
> > > 这个是安卓代码初始化问题
> > 
> > 
> > 我看了一下，不太好处理，你有什么解决办法吗？
> 
> 你们也是应用市场上不去？ 还是用什么规避方案先上市场

华为和小米的应用市场都有这个问题，还没上

**Comment by XT-0515** [comment]
> 

有进展及时沟通🤝

**Comment by XT-0515** [comment]
> 这个项目的作者不知道什么时候能处理，我在试着本地改下。

有进展及时沟通🤝

**Comment by huangnan78100** [comment]
> > 这个项目的作者不知道什么时候能处理，我在试着本地改下。
> 
> 有进展及时沟通🤝

okok

**Comment by hengkx** [comment]
有什么进展吗 我也遇到了

**Comment by XT-0515** [comment]
> 有什么进展吗 我也遇到了

暂时没有进展。。

**Comment by XT-0515** [comment]
@huangnan78100 @hengkx  方便进群交流一下吗~ 
![交流群二维码](https://user-images.githubusercontent.com/47058891/198927272-398caf8f-1a1d-4f3d-991c-643084ee7866.jpg)

**Comment by XT-0515** [comment]
暂时解决方案：https://github.com/XT-0515/react-native-orientation-locker/commit/0d758b98b97a67e8d0cd5dacf7183f590090f2a4

**Comment by RevivalDev** [comment]
> 暂时解决方案：https://github.com/XT-0515/react-native-orientation-locker

您好，我按照您上面的方式好像在小米还是审核不通过，那个微信群的二维码方便再发一次吗？我想加群请教一下

**Comment by Snooker-shoot** [comment]
@XT-0515 你好，请问你解决了吗？能分享一下解决方案吗

**Comment by XT-0515** [comment]
> > 临时解决方案：https://github.com/XT-0515/react-native-orientation-locker
> 
> 您好，我按您上面的方式好象在小米还是审核不过，那个微信群的二维码方便再发一次吗？我想加群请教一下
vx: Positive_005

**Comment by mynameisliuyurong** [comment]
![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/78694d12-5f3b-436a-b656-84f4f493ded3)
The author here initialized the screen listener to listen for sensor changes, I think just delay the initialization (new OrientationEventListener), when it needs to be properly initialized you need to send a notification using rn and native interaction to tell it to initialize, Of course, this requires some android skills.

**Comment by moonlight1002** [comment]
> ![image](https://user-images.githubusercontent.com/30228287/260415541-78694d12-5f3b-436a-b656-84f4f493ded3.png) The author here initialized the screen listener to listen for sensor changes, I think just delay the initialization (new OrientationEventListener), when it needs to be properly initialized you need to send a notification using rn and native interaction to tell it to initialize, Of course, this requires some android skills.



> ![image](https://user-images.githubusercontent.com/30228287/260415541-78694d12-5f3b-436a-b656-84f4f493ded3.png) The author here initialized the screen listener to listen for sensor changes, I think just delay the initialization (new OrientationEventListener), when it needs to be properly initialized you need to send a notification using rn and native interaction to tell it to initialize, Of course, this requires some android skills.



> ![image](https://user-images.githubusercontent.com/30228287/260415541-78694d12-5f3b-436a-b656-84f4f493ded3.png) The author here initialized the screen listener to listen for sensor changes, I think just delay the initialization (new OrientationEventListener), when it needs to be properly initialized you need to send a notification using rn and native interaction to tell it to initialize, Of course, this requires some android skills.

Yes, can you provide a pull request？Thanks

**Comment by moonlight1002** [comment]
> ![image](https://user-images.githubusercontent.com/30228287/260415541-78694d12-5f3b-436a-b656-84f4f493ded3.png) The author here initialized the screen listener to listen for sensor changes, I think just delay the initialization (new OrientationEventListener), when it needs to be properly initialized you need to send a notification using rn and native interaction to tell it to initialize, Of course, this requires some android skills.

Yes, can you provide a pull request？Thanks

**Comment by mynameisliuyurong** [comment]
[code.zip](https://github.com/wonday/react-native-orientation-locker/files/12340893/code.zip)
替换对应的文件,他们分别位于
![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/b53b276b-8ee8-414d-966b-7c8962e69733)
像这样使用
![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/adf6bc8e-f30e-421a-ac4b-8759f6950592)
日志输出没问题！
![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/de0fe18c-cf02-4f7b-90d7-d17a848e2ee8)

![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/0eec29c0-d710-40ae-87bf-ad8a904805cf)

**Comment by lyrpromax** [comment]
> [code.zip](https://github.com/wonday/react-native-orientation-locker/files/12340893/code.zip) 替换对应的文件同时init初始化了传感器，removeInit删除了传感器，但是你需要对系统做判断，Android才需要执行init和remove ![图像](https://user-images.githubusercontent.com/30228287/260616777-b53b276b-8ee8-414d-966b-7c8962e69733.png)
> 
> ![图像](https://user-images.githubusercontent.com/30228287/260616919-adf6bc8e-f30e-421a-ac4b-8759f6950592.png)
> 
> ![图像](https://user-images.githubusercontent.com/30228287/260617040-de0fe18c-cf02-4f7b-90d7-d17a848e2ee8.png)
> 
> ![图像](https://user-images.githubusercontent.com/30228287/260617067-0eec29c0-d710-40ae-87bf-ad8a904805cf.png)

![image](https://github.com/wonday/react-native-orientation-locker/assets/30228287/d3b0b851-c38b-432d-8ce6-91d52e5a5328)
商店审核已通过 测试，这样改看起来没问题。

**Comment by izozo** [comment]
你好，请问你解决这个问题了吗？我现在上架华为也遇到了这种情况。

**Comment by moon-xt** [comment]
> I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)

@izozo 解决方案在这

**Comment by izozo** [comment]
> > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)
> 
> @izozo 解决方案在这

最新版本有解决完这个问题吗 我看了下你上面提到的改动比较大- - 我项目上的库是去年的

**Comment by moon-xt** [comment]
> > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)我提交了一个分支来解决这个问题#270（评论）
> > 
> > 
> > @izozo 解决方案在这
> 
> 最新版本有解决完这个问题吗 我看了下你上面提到的改动比较大- - 我项目上的库是去年的

这个问题的pr作者没合并，固定版本号，自行patch打补丁吧

**Comment by izozo** [comment]
> > > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)我提交了一个分支来解决这个问题#270（评论）
> > > 
> > > 
> > > @izozo 解决方案在这
> > 
> > 
> > 最新版本有解决完这个问题吗 我看了下你上面提到的改动比较大- - 我项目上的库是去年的
> 
> 这个问题的pr作者没合并，固定版本号，自行patch打补丁吧

痛苦嘞

**Comment by PDxixiangkeren** [comment]
> > > > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)我提交了一个分支来解决这个问题#270（评论）
> > > > 
> > > > 
> > > > @izozo 解决方案在这
> > > 
> > > 
> > > 最新版本有解决完这个问题吗 我看了下你上面提到的改动比较大- - 我项目上的库是去年的
> > 
> > 
> > 这个问题的pr作者没合并，固定版本号，自行patch打补丁吧
> 
> 痛苦嘞

哥们怎么样了

**Comment by izozo** [comment]
> > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)
> > 
> > 
> > @izozo 解决方案在这
> 
> 1.5.0版本都没有这两个方法咋搞

我查了下项目用到这里的地方不多 我直接去掉这个库了。。。

**Comment by PDxixiangkeren** [comment]
> > > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)
> > > 
> > > 
> > > @izozo 解决方案在这
> > 
> > 
> > 1.5.0版本都没有这两个方法咋搞
> 
> 我查了下项目用到这里的地方不多 我直接去掉这个库了。。。
难搞

**Comment by PDxixiangkeren** [comment]
> > > > I submitted a branch to solve this problem [#270 (comment)](https://github.com/wonday/react-native-orientation-locker/pull/270#issue-1854637859)
> > > 
> > > 
> > > @izozo 解决方案在这
> > 
> > 
> > 1.5.0版本都没有这两个方法咋搞
> 
> 我查了下项目用到这里的地方不多 我直接去掉这个库了。。。

难搞啊

**Comment by hdjhdjhdj** [comment]
https://github.com/hashencode/react-native-orientation-locker-cn
看看这个，他整理的
