### ISSUE TITLE
iOS lockToPortrait always returns Portrait on orientation change

### ISSUE THREAD

**Issue by nicholasc** [wonday/react-native-orientation-locker#26]
Using `Orientation.lockToPortrait` on iOS works fine but when the device orientation changes, the value returned is always 'portrait'. 

I guess this would be the expected result but what if I want to keep the device visually locked to portrait and want to trigger a special overlay when it is rotated to landscape.

**Comment by wonday** [comment]
I have added deviceOrientation at v1.0.21

**Comment by nicholasc** [comment]
This is exactly what I needed. 
Thank you very much.

**Comment by msageryd** [comment]
Great! 
I had to add some accelerometer data to get hold of the orientation when screen was locked. Thought that it was by design, and worked around it. But it seems that this is now unnecessary. I'll upgrade and see if I can get rit of my workaround.
