### ISSUE TITLE
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 

### ISSUE THREAD

**Issue by LuckyMona** [wonday/react-native-orientation-locker#27]
Hello, 

When using `react-native link react-native-orientation-locker`, I got this error. I thought that maybe it's because I didn't install rnpm，so I install it and tried again, but it still report the error.

This is the log:
react-native link react-native-orientation-locker
Scanning folders for symlinks in /Users/tianmiao185/Documents/Projects/smartcitycard/node_modules (17ms)
rnpm-install info Linking react-native-orientation-locker ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'match' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 

Cannot read property 'match' of undefined

thank you for your work!

**Comment by ali-sao** [comment]
Facing something similar when linking with react native :

```
Scanning folders for symlinks in /node_modules (13ms)
rnpm-install ERR! ERRPACKAGEJSON No package found. Are you sure this is a React Native project?
Invalid attribute name
Line: 15
Column: 9
Char: <

```

**Comment by wonday** [comment]
please see https://github.com/facebook/react-native/issues/16774
