### ISSUE TITLE
haste module naming collision

### ISSUE THREAD

**Issue by ZeroCool00** [wonday/react-native-orientation-locker#28]
i just install this library and configure pod, when i try to run my project i get this error

UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-native
  Paths: /MyDrive/Projects/React/xxx/node_modules/react-native/package.json collides with /MyDrive/Projects/React/xxx/ios/Pods/React/package.json

if i remove this library, project start working again..  

```
"react": "16.6.0-alpha.8af6728",
 "react-native": "0.57.4",
"react-native-orientation-locker": "^1.0.19",
```

is it necessary to use pod?  when i execute "pod install" it install two module 
1. react 
2. react-native-orientation-locker

why react? and its also a deprecated react.

**Comment by wonday** [comment]
I am not very familiar with pod,  just copy this from others.
anyone can confirm this?

**Comment by gp3gp3gp3** [comment]
This is related to React Native, not this library.  You're running into issues installing the native code using cocoapods.  You'll have to link the node module manually per the RN docs.

**Comment by ZeroCool00** [comment]
No, this is related to this lib.. and here is the solution:

whenever you install some of the library using pod, it install react library with it, to ignore that you need to write this code in pod.

```
post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name != "React"
              
          if target.name == "React"
              target.remove_from_project
          end
      end
  end
```
