### ISSUE TITLE
package for RN 0.73.1 ?

### ISSUE THREAD

**Issue by Productivix** [wonday/react-native-orientation-locker#284]
hi, 
the new version of RN , 0.73.1 affects MainActivity.java in .kt : do you please have a transcription of the commands to insert in kt ?
thanks

**Comment by Productivix** [comment]
in reply to myself , 
I tested : in RN 0.73.1
in mainActivity.kt  and in mainApplication.kt , I added **nothing** and it runs .

**Comment by the-mysterious-kid** [comment]
I added the following code `MainActivity.kt' instead of the one suggested in Readme

> override fun onConfigurationChanged(newConfig: Configuration) {
      super.onConfigurationChanged(newConfig)
      val intent = Intent("onConfigurationChanged")
      intent.putExtra("newConfig", newConfig)
      sendBroadcast(intent)
}

And it worked for me
