### ISSUE TITLE
lockToPortrait not always working

### ISSUE THREAD

**Issue by assafb81** [wonday/react-native-orientation-locker#29]
Hi,
Great package, solved a lot of issues I had with `react-native-orientation`.

My scenario is this:

1. app is `lockToPortrait` when initialized -> working great
2. moving to a screen with video -> the app still locked in portrait, but now `addOrientationListener` is added.
3. rotate the device, the app remain in portrait (the app is still locked)
4. playing video -> `unlockAllOrientations`
5. rotating device -> video in full screen, in landscape.
6. pressing device back button when device **remains** in landscape orientation:
6.1 rotating video, existing full screen
6.2 `lockToPortrait` again

**Actual result**: app remain in landscape orientation in some Android devices and in some it rotate to portrait
**Expected result**: app rotate to portrait.

7. press device back button again, while device **remains** in landscape orientation.

**Actual result**: app rotate to portrait.
**Expected result**: app rotate to portrait.

I did debugging and this is what I found.
In `onOrientationChanged` method in `OrientationModule.java` file. 
In line 70, the value is set to PORTRAIT: `deviceOrientationValue = "PORTRAIT";`
but in line 84, if `isLocked` is true than `getCurrentOrientation` method is called.
Now, `isLocked` flag is true, since in my JS I used `Orientation.lockToPortrait` method which set `isLocked` flag to true.
And in `getCurrentOrientation` method, since the device orientation is LANDSCAPE, the return value is `LANDSCAPE-XXX`.

I think that the problem is in line 181, `setRequestedOrientation` does not work properly in`lockToPortrait` method?

Maybe there is a need to add delay, some kind of timeout to make sure the lock will "catch"?

@wonday , What do you think?

**Comment by wonday** [comment]
```
pressing device back button when device remains in landscape orientation:
6.1 rotating video, existing full screen
6.2 lockToPortrait again
```
you should ```lockToPartrait``` in back button process, Are you call here?

```getCurrentOrientation``` return the UI orientation, not the device orientation, 
so if you called ```lockToPartrait``` and then ```getCurrentOrientation```,
it should return ```PORTRAIT```

if you do above and still have problem, maybe ```setRequestedOrientation``` need some delay...

**Comment by wonday** [comment]
lockToXXX will lock UI, UI will not change when rotation.
after call lockToXXX, when rotation, you can receive event by ```addOrientationListener(function(orientation,deviceOrientation))```
and orientation(UI) will be not changed, deviceOrientation will be change.
