### ISSUE TITLE
React Native Orientation

### ISSUE THREAD

**Issue by andrerfneves** [wonday/react-native-orientation-locker#3]
How is this different than [react-native-orientation](https://github.com/yamill/react-native-orientation)? The code is almost exactly the same.

**Comment by wonday** [comment]
react-native-orientation was no maintenance for a long time. (It is reactive recently)
When I want to use it, I found it can not work at RN 0.40 and had some bugs.
I rewrite the codes specially in android, I add the sensor check and make it more accurate.

**Comment by andrerfneves** [comment]
Ok thanks.
