### ISSUE TITLE
iOS pod instructions didn't work

### ISSUE THREAD

**Issue by Sean-Brown-Digi** [wonday/react-native-orientation-locker#34]
In the README it says to do 
`pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'`
however this produces an error for me:
```
An error occurred while redirecting file '../node_modules/react-native-orientation-locker'
open: Is a directory
```
The following command worked for me:
`pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker/react-native-orientation-locker.podspec`

**Comment by wonday** [comment]
Thank you, I will fixed it at next release.
