### ISSUE TITLE
[iOS] Native module cannot be null.

### ISSUE THREAD

**Issue by devonhuangcodes** [wonday/react-native-orientation-locker#39]
I manually linked this library and it works perfectly on Android. On iOS, it also works fine when I run the app through xcode. However, when I try to run the app through react-native-cli using the command react-native run-ios, I get the following error:

> Native module cannot be null.

<img width="282" alt="screen shot 2018-12-11 at 1 33 22 pm" src="https://user-images.githubusercontent.com/39835747/49821883-845e1b80-fd49-11e8-8f91-c45c6b6f64ec.png">

**Comment by emilany** [comment]
Also experiencing the same issue, any fix or workaround?

**Comment by devonhuangcodes** [comment]
Yup I have already tried that

**Comment by paulxuca** [comment]
If it works via xcode and not through cli, it might mean that you're running an old version of the app in simulator without the native code built. I would double check that the right app is being launched when  you start the app via cli.

**Comment by devonhuangcodes** [comment]
I'm not too sure what I did or what happened. It might've been resolved when I did a clean build to fix a previous issue. I just tried running it using the cli just now and it started working. Closing this issue. Thanks for your insights Paul

**Comment by truongluuxuan** [comment]
Right click to Libraries in xcode, chose add newnew file to "your project", find in node_module , open react-native-orientaion-locker , chose RCTOrientationation.xcodeproj, Go to Build Phases, in Link BinariesBinary with Libraries, add libRCTOrientation.a. enjoy

**Comment by LAITONEN** [comment]
> Right click to Libraries in xcode, chose add newnew file to "your project", find in node_module , open react-native-orientaion-locker , chose RCTOrientationation.xcodeproj, Go to Build Phases, in Link BinariesBinary with Libraries, add libRCTOrientation.a. enjoy

From step 2.
1. Add `${ROOT}/node_nodules/react-native-orientation-locker/iOS/RCTOrientation.xcodeproj` to `XCode -> ${YOUR_PROJECT_NAME}/Libraries`
2. Click on `${YOUR_PROJECT_NAME}, open `Build Phases - Link Binary With Libraries`
3. In the folder from step 1,  find `Products/libRCTOrientation.a`, and drag-drop it to the list of Binaries from the step 2.
