### ISSUE TITLE
Orientation.h not found error in AppDelegate.m

### ISSUE THREAD

**Issue by tolgaduzenli** [wonday/react-native-orientation-locker#4]
RN version is : "0.43.3",
My package.json content is;
{
  "name": "FirstApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@shoutem/theme": "^0.9.0",
    "@shoutem/ui": "^0.15.0",
    "install": "^0.10.1",
    "npm": "^5.3.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-fcm": "^1.0.15",
    "react-native-orientation-locker": "^1.0.3",
    "react-native-tab-view": "0.0.66",
    "react-navigation": "^1.0.0-beta.11"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

RCTOrientation.xcodeproj  is built successfully. 

AppDeletage.m imports are ;
#import "AppDelegate.h"
#import "React/RCTBundleURLProvider.h"
#import "React/RCTRootView.h"
#import "Orientation.h"
#import "RNFIRMessaging.h"

Header search paths of my project;All of them recursive.
$(inherited)
$(SRCROOT)/../../react-native/React
$(SRCROOT)/../../react-native/Libraries
$(SRCROOT)/../node_modules/react-native-fcm/ios

And still getting same error. What should I do ?

**Comment by wonday** [comment]
It should added automatically, some reason, it was not added.
You can add $(SRCROOT)/../node_modules/react-native-orientation-locker/iOS/RCTOrientation recursive

**Comment by tolgaduzenli** [comment]
Now it is ok, Thanks a lot.

**Comment by jpcarts23** [comment]
#import "../../node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.h"

or

(In AppDelegate.m)
#import "Orientation.h"

(In Header Search Path)(make sure it is recursive)
$(SRCROOT)/../node_modules/react-native-orientation/iOS/RCTOrientation

**Comment by bdelville** [comment]
More exactly:
#import "../../node_modules/react-native-orientation-locker/iOS/RCTOrientation/Orientation.h"

**Comment by rickcha** [comment]
@jpcarts23 it's $(SRCROOT)/../node_modules/react-native-orientation-locker/iOS/RCTOrientation not $(SRCROOT)/../node_modules/react-native-orientation/iOS/RCTOrientation

**Comment by pritasam** [comment]
Not working :((
