### ISSUE TITLE
On Changing Orientation on simulator

### ISSUE THREAD

**Issue by ajaysinghthakur** [wonday/react-native-orientation-locker#40]
Environment : ios,
simulator: iPhone X,
xcode 10

when i change the orientation on simulator to check weather it's working i got the following error-

**`deviceOrientationDidChange` is not a supported event type for Orientation. Supported events are: `orientationDidChange`**

**Comment by kumaresan-cgvak** [comment]
I too face the same issue with the latest version of react-native-orientation-locker.
<img width="317" alt="screenshot 2018-12-19 at 8 05 35 pm" src="https://user-images.githubusercontent.com/5547152/50226536-794e5f80-03c9-11e9-97ce-621803714dad.png">

**Comment by kumaresan-cgvak** [comment]
> Environment : ios,
> simulator: iPhone X,
> xcode 10
> 
> when i change the orientation on simulator to check weather it's working i got the following error-
> 
> **`deviceOrientationDidChange` is not a supported event type for Orientation. Supported events are: `orientationDidChange`**

@ajaysinghthakur Do you face it in Device as well?

**Comment by ajaysinghthakur** [comment]
@kumaresan-cgvak not tested yet

**Comment by asfreng-returns** [comment]
i got the same error in a device @kumaresan-cgvak

**Comment by wonday** [comment]
OK，let me check it, and android is OK?

**Comment by wonday** [comment]
are you only add `addOrientationListener()` ?
add both
```
        Orientation.addOrientationListener(this._onOrientationDidChange);
        Orientation.addDeviceOrientationListener(this._onDeviceOrientationDidChange);
```
try again?

**Comment by kumaresan-cgvak** [comment]
@wonday even after ading both listners we still face the issue.

**Comment by asfreng-returns** [comment]
@wonday In the error im getting "RTCEventEmitter sendEventWithName: body:" instead of "addlistener", it triggers when i rotate the device.

**Comment by scottmas** [comment]
Just verified that this error does not occur on v1.0.22

**Comment by wonday** [comment]
I confirmed, it only happen in Debug version, and release version no problem.
```
RCTEventEmitter.m:76

  if (RCT_DEBUG && ![[self supportedEvents] containsObject:eventName]) {
    RCTLogError(@"`%@` is not a supported event type for %@. Supported events are: `%@`",
                eventName, [self class], [[self supportedEvents] componentsJoinedByString:@"`, `"]);
  }
```
I do not known why RN add this to debug only.

I had fixed it at master, anybody can test it?

**Comment by asfreng-returns** [comment]
@wonday working perfect testing from master on an ios device, great job!

**Comment by wonday** [comment]
@asfreng-returns 
thanks, I have release it to v1.1.1.

**Comment by ajaysinghthakur** [comment]
@wonday working tested v1.1.1. thank's
