### ISSUE TITLE
Locking to Portrait on app launching rotates from Landscape to Portrait (iOS)

### ISSUE THREAD

**Issue by vladinko0** [wonday/react-native-orientation-locker#42]
I want to lock the orientation of the first screen of app to Portrait. But when I launch the application I see for a while landscape orientation and then quickly rotating to the Portrait orientation. Next screens are okey.

Here is my code:

```
componentDidMount() {
        Orientation.lockToPortrait()
}
```

Is it possible to solve this performance issue?

**Comment by vladinko0** [comment]
I am using v. 1.0.8

**Comment by wonday** [comment]
You also can add native code to AppDelegate.m

```
#import "Orientation.h"

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // lock to Portrait
  [Orientation setOrientation:UIInterfaceOrientationMaskPortrait];
  [[UIDevice currentDevice] setValue:[NSNumber numberWithInteger: UIInterfaceOrientationPortrait] forKey:@"orientation"];

...
}
```

**Comment by vladinko0** [comment]
It was my error.
I used in one class redundant code:

    const setLandscapeRightOrientation = Platform.select({
        ios: Orientation.lockToLandscapeRight(),
        android: Orientation.lockToLandscapeLeft(),
    });

**Comment by ALPNP** [comment]
The native code solved my problem. This is amazing. I love this library.
