### ISSUE TITLE
Orientation.lockToPortrait(), but is there a way to detect if it's in landscape or portrait

### ISSUE THREAD

**Issue by RukaiJohn** [wonday/react-native-orientation-locker#43]
I have portrait to locked, but I want specific items (buttons and text) to rotate if phone is rotated either to landscape or portrait. 

Here is what I did:

  _onOrientationDidChange = orientation => {
    if (orientation == "LANDSCAPE-LEFT" || orientation == "LANDSCAPE-RIGHT") {
      alert("landscape");
    } else {
      alert("portrait");
    }
  };

  componentDidMount() {
    Orientation.lockToPortrait();
    Orientation.addOrientationListener(this._onOrientationDidChange);
  }

 componentWillUnmount() {
    Orientation.removeOrientationListener(this._onOrientationDidChange);
  }

**Comment by wonday** [comment]
You can use ```addDeviceOrientationListener(function(deviceOrientation))``` to listen the device orientation.
you can also use ```getDeviceOrientation(function(deviceOrientation))``` to get current device orientation.

Device orientation will not be affected by lockToXXX

**Comment by RukaiJohn** [comment]
Thank you. It worked really well
