### ISSUE TITLE
android first open app then back Mobile desktop . go back android app  repeated execution (componentWillMount)

### ISSUE THREAD

**Issue by zhilianghuang** [wonday/react-native-orientation-locker#44]
`componentWillMount() {
		alert(' frist ');
		var initial = Orientation.getInitialOrientation();
		if (initial === 'PORTRAIT') {
			//do stuff
		} else {
			//do other stuff
		}
	}

componentDidMount() {
		Orientation.getAutoRotateState((rotationLock) => this.setState({ rotationLock }));
		Orientation.lockToLandscape();
		Orientation.addOrientationListener(this._onOrientationDidChange);
	}

	componentWillUnmount() {
		AppState.removeEventListener('change', this._handleAppStateChange);

		 // Remember to remove listener
		Orientation.removeOrientationListener(this._onOrientationDidChange);
	}

	_onOrientationDidChange = (orientation) => {
		if (orientation == 'LANDSCAPE-LEFT') {
			//do something with landscape left layout
		} else {
			//do something with portrait layout
		}
	};```

**Comment by wonday** [comment]
Is Your problem ```android app repeated execution (componentWillMount)``` ?
This is react-native problem, not this module.

**Comment by zhilianghuang** [comment]
Thanks no problem
