### ISSUE TITLE
[android] Orientation.unlockAllOrientations () does not work

### ISSUE THREAD

**Issue by kraksin** [wonday/react-native-orientation-locker#46]
I'm using react-navigation,
In the previous screen, I used lockToPortrait () to prevent landscape.

In the next screen, I was working on unlockAllOrientations () to make the landscape change possible.

But unlockAllOrientations () does not work on Android!
The addDeviceOrientationListener obviously changes, but the UI does not change.

Is there a way to solve it? I need help

The problem only occurs with Android.
iOS works fine.

lock landscape screen
```
componentDidMount = () => {
    this.getFeedData();
    setTimeout(() => {
      Orientation.lockToPortrait();
    }, 10);
  };
```

I was going to go to the next screen and unlock it using unlockAllOrientations ().

unlock screen
```
componentDidMount = () => {
    BackHandler.addEventListener('hardwareBackPress', this.handleBackPress);
    Orientation.addDeviceOrientationListener(this.onOrientationDidChange);
    Orientation.unlockAllOrientations();
  }
```

android version
```
buildToolsVersion = "28.0.3"
minSdkVersion = 19
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"
```

I run it with version 8.1 Android emulator.
react-native-orientation-locker, use 1.1.1 version now

**Comment by RukaiJohn** [comment]
Did you ever get this to work?

**Comment by wonday** [comment]
unlockallorientations() just unlock, does not change UI orientation, 
when you rotate your device, does UI change?
BTW, confirm your device system setting is not locking orientation.

**Comment by kraksin** [comment]
I did a new parsing of the project for testing and it worked fine.
I did not know the exact reason.

I am applying the code based on the test project.

**Comment by kraksin** [comment]
found!

In styles.xml on Android
<item name = "android: windowIsTranslucent"> true </ item>

If you comment out this, it works perfectly on Android.

**Comment by mitrahBala** [comment]
Hi guys I am using react-native camera for barCode scan. When componentMount I lock the device orientation into Landscape. When componentWillUnmount I used unlockAllOrientations. But the device remains the Landscape only in IO. In android it works fine. Anyway to fix this in IOS.
