### ISSUE TITLE
undefined is not an object (evaluating 'OrientationNative.initialOrientation)

### ISSUE THREAD

**Issue by sashaba** [wonday/react-native-orientation-locker#47]
Hello
I'm trying to lock my app orientation to portrait using this repo, but I get this error:
TypeError: undefined is not an object (evaluating 'OrientationNative.initialOrientation)

Below is the code I'm using. I really appreciate any help you can get me. Thank you.
```
_onOrientationDidChange = (orientation) => {
    if (orientation == 'LANDSCAPE-LEFT') {
      alert("landscape");
    } else {
      alert("portrait");
    }
  };
componentWillMount() {
	   var initial = Orientation.getInitialOrientation();
    if (initial === 'PORTRAIT') {
      alert ("portrait");
    } else {
      alert ("landscape");
    }
}

async componentDidMount() {
	  Orientation.getAutoRotateState((rotationLock) => this.setState({rotationLock}));
	   Orientation.lockToPortrait();
	   Orientation.addOrientationListener(this._onOrientationDidChange);
}

**Comment by sashaba** [comment]
here a screenshot of the error

![pic6](https://user-images.githubusercontent.com/40736543/51422819-9d958b80-1b83-11e9-8989-9bb92c0af212.jpg)

thank you.

**Comment by wonday** [comment]
it seems not linking OK, 
run ```react-native link react-native-orientation-locker``` again
