### ISSUE TITLE
unlockAllOrientations() not working

### ISSUE THREAD

**Issue by RukaiJohn** [wonday/react-native-orientation-locker#48]
Let me say that this is a great pluggin for react native. But I have an issue

In the first screen, I locked to portrait, but in my second screen, I called unlockallorientations(), but it's not working. The second screen is still locked to portrait. Is there a way to fix this?

**Comment by wonday** [comment]
unlockallorientations() just unlock, does not change UI orientation, 
when you rotate your device, does UI change?  
BTW, confirm your device system setting is not locking orientation.

**Comment by RukaiJohn** [comment]
Sorry for the late reply.  When I rotate my device, the UI does not change. I also checked my device system settings, but it's not working.

**Comment by olinations** [comment]
Any more info on this? I have the same situation. I nav to new screen and lock to landscape, onBack I unlock orientation but it does not unlock. It stays in landscape no matter how I move my phone. 

I have tried unlocking at different points. I even added it to a button that when clicked unlocks the orientation. None work. 

I can change it from landscape to to portrait no problem, but I cannot unlock it no matter what I try.

**Comment by yberstad** [comment]
I know this is an old thread, but I solved it like this:

```
export const unlockAllOrientationsAsync = async (context: string): Promise<void> => {
  return new Promise((resolve) =>
    setTimeout(() => {
      Tracer.trace("unlockAllOrientationsAsync " + context);
      Orientation.unlockAllOrientations();
      resolve();
    }, 1000),
  );
};
```
