### ISSUE TITLE
ios use question

### ISSUE THREAD

**Issue by s349856186** [wonday/react-native-orientation-locker#49]
My app only has one screen that will be displayed landscape under certain conditions, otherwise all screens it is always Portrait screen, so IOS must be set the orientation "Portrait" and "Landscape Left" in xcode ?

**Comment by wonday** [comment]
Check all or check only you use.
and you should also control by code.
call lockPartrait() at app start and call lockLandscape at landscape page, and call lockPartrait() again when leave landscape page.

**Comment by s349856186** [comment]
https://github.com/facebook/react-native/issues/11036

**Comment by kaystd** [comment]
@s349856186 Thanks! You save lot of my hours
