### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by efstathiosntonas** [wonday/react-native-orientation-locker#5]
There is a typo in readme

` pod 'react-native-orientation-locker', :path => 'node_modules/react-native-orientation-locker' `

should be: 

`pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation-locker'`

otherwise throws error `No podspec found for react-native-orientation-locker in node_modules/react-native-orientation-locker ` when running `pod install` inside the `ios` folder of the project.

**Comment by wonday** [comment]
Thank you for your info.
I have fixed it at github and will release to npm at next version.
