### ISSUE TITLE
Android - lockToPortrait does not work.

### ISSUE THREAD

**Issue by mauricioscotton** [wonday/react-native-orientation-locker#50]
I've tried to make it work as described on the main page, but it does not works.
`
import React from 'react';
import Orientation from 'react-native-orientation-locker';

export default class LoginScreen extends React.Component {
    constructor(props){
        super(props);
    }    
    componentDidMount(){
        Orientation.lockToPortrait();
    }
`
![image](https://user-images.githubusercontent.com/34411735/52360361-b8954600-2a33-11e9-90a6-a8a7f98daedc.png)

**Comment by wonday** [comment]
check your android AndroidManifest.xml
confirm if orientation was added.
```
android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
```


and see demo https://github.com/wonday/react-native-pdf/tree/master/example

**Comment by mauricioscotton** [comment]
> check your android AndroidManifest.xml
> confirm if orientation was added.
> 
> ```
> android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
> ```
> and see demo https://github.com/wonday/react-native-pdf/tree/master/example

Thanks a million for your answer!
I've been digging out on internet and realized that the problem was RNN.
They have a few hooks and therefore was blocking all my attempts to lock the screen.
I've tried before doing it natively, but RNN was taking care of it.

Once again, thanks a million!
Cheers
