### ISSUE TITLE
RN 0.58 + Android target SDK 27 = Problem with orientation locker

### ISSUE THREAD

**Issue by radeno** [wonday/react-native-orientation-locker#55]
Hi,

its looks like that Android by SDK 27 and up change ability to locking screen which are not fullscreen.
It is only issue when target SDK is set to 27, which is default in RN 0.58. But when is compiled with target SDK 26 it works.
Error:
`Issue: java.lang.IllegalStateException: Only fullscreen activities can request orientation`

Any hints how to fix it without any complex solution ? Maybe add oneliner into AndroidManifest.xml ?

Same issues in different repositories
https://github.com/Instabug/Instabug-Android/issues/68
https://github.com/ParkSangGwon/TedPermission/issues/63

**Comment by radeno** [comment]
I have digging down and this is problem just with RN 0.58 branch. Because combination target SDK 27 and ReactActivity extending from Activity.

RN 0.59 extending from AppCompatActivity which will fix it.
More about issue in this link: https://stackoverflow.com/questions/49124073/how-to-restrict-screen-orientation-to-portrait-in-android-sdk-27

**Comment by radeno** [comment]
Simple working fix is disabling translucent feature
in file `android/app/src/main/res/values/styles.xml` replace:
```xml
<item name="android:windowIsTranslucent">true</item>
```
to
```xml
<item name="android:windowIsTranslucent">false</item>
```

Maybe this can be noticed in Readme file

**Comment by wonday** [comment]
I had add this notice to readme.

**Comment by asfreng-returns** [comment]
Im having the same issue with RN 0.59.0 and SDK 28

**Comment by ggunti** [comment]
I don't think that the version of react-native matters, I get the error also with RN 0.61.5 on android 8. I'll try @radeno  solution.

**Comment by wilau2** [comment]
The problem with @radeno solution is that it breaks the `https://github.com/crazycodeboy/react-native-splash-screen` that requires `<item name="android:windowIsTranslucent">true</item>` to be nice and smooth.

By making this fix, your splashscreen will have a white flash instead of being nice and smooth.
