### ISSUE TITLE
this._nativeModule.addListener is not function error

### ISSUE THREAD

**Issue by erdouzun** [wonday/react-native-orientation-locker#56]
Hi,

I got this error, when I try to use orientation-locker.

RN version 0.58

  componentDidMount() {
        Orientation.lockToPortrait();
Orientation.addOrientationListener(this._onOrientationDidChange);
      }

_onOrientationDidChange = (orientation) => {
        if (orientation == 'LANDSCAPE') {
          //do something with landscape left layout
        } else {
          //do something with portrait layout
        }
      };

**Comment by JinghaoYJH** [comment]
try this, it works for me
Orientation.addOrientationListener((orientation) => {this._orientationDidChange()})

**Comment by erdouzun** [comment]
I used "react-native-orientation" instead "react-native-orientation-locker". thanks for your replies.
