### ISSUE TITLE
Undefined is not an object (evaluating 'OrientationNative.lockToPortrait')

### ISSUE THREAD

**Issue by hufkens** [wonday/react-native-orientation-locker#58]
I followed all the linking steps in the ReadMe and still get this error.
```
undefined is not an object (evaluating 'OrientationNative.lockToPortrait')
lockToPortrait
    index.js:47:26
<unknown>
    App.js:16:2
loadModuleImplementation
    require.js:320:6
<unknown>
    index.js:5
loadModuleImplementation
    require.js:320:6
guardedLoadModule
    require.js:207:45
global code
```
In my App.js I have:
```
import Orientation from 'react-native-orientation-locker'; 
Orientation.lockToPortrait();
```
Any idea what I am doing wrong?

**Comment by mdmush** [comment]
Is it happening in both Android and iOS?

**Comment by hufkens** [comment]
Only Android. On iOS it works perfect

**Comment by mdmush** [comment]
Okay.

Maybe the linking is not done properly.
Can you check if these files have these lines in them added?

#### 1. android/settings.gradle

    include ':react-native-orientation-locker'
    project(':react-native-orientation-locker').projectDir` = new File(rootProject.projectDir, '../node_modules/react-native-orientation-locker/android')

#### 2. android/app/build.gradle

    dependencies {
         ...
         compile project(':react-native-orientation-locker')
         ...
    }

#### 3. android/app/src/main/java/.../android/MainActivity.java

    @Override
     public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        Intent intent = new Intent("onConfigurationChanged");
        intent.putExtra("newConfig", newConfig);
        this.sendBroadcast(intent);
    }

#### 4. android/app/src/main/java/.../android/MainApplication.java

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new OrientationPackage()
      );

**Comment by hufkens** [comment]
Looks like it's a local issue with my setup. Somebody else from the team got it working correctly. If I find out what's wrong I'll come back to this.
