### ISSUE TITLE
Can we have the function to check if the screen is locked?

### ISSUE THREAD

**Issue by truongluong1314520** [wonday/react-native-orientation-locker#59]
Hi @wonday , first of all, I really want to say thank you for continue this awesome project and did awesome things to improve it.

My question is that can we have a function to check if the screen is already locked by the library (not from Android Manifest or iOS Xcode).

Here is my case, I have a swipe view and the condition is that:
1/ Image: lock portrait
2/ Video: unlock

So when users swipe, library will keep calling the function lock screen, which sounds redundant, right?

If there is a way to check, please let me know.

Thank you again for the great work! 👍

**Comment by wonday** [comment]
I have add Orientation.isLocked() to master, and will be release after test.
You can try it first.

**Comment by truongluong1314520** [comment]
Hi @wonday , thank you so much for the reply 😄
