### ISSUE TITLE
iOS build fail after adding library

### ISSUE THREAD

**Issue by truongluong1314520** [wonday/react-native-orientation-locker#60]
Hi @wonday , it is me again. I just run my project in Xcode and suddenly the build is fail.

Here is the image for the error report:

![Screen Shot 2019-03-19 at 10 51 56 AM](https://user-images.githubusercontent.com/32918401/54579222-0dfe4300-4a35-11e9-8569-03fd51db82bd.png)

My installation steps:
1/ I typed `react-native link react-native-orientation-locker`
2/ Add import and the required function
3/ Add $(SRCROOT)/../node_modules/react-native-orientation-locker/iOS/RCTOrientation 

UPDATE
======

When I comment the required function in AppDelegate.m. The project is able to be built

Please help me out... Thank you in advance!

**Comment by truongluong1314520** [comment]
Hi @wonday , I don't know why but this one work for me:

`#import "../../node_modules/react-native-orientation-locker/iOS/RCTOrientation/Orientation.h"`

I try this one in the Header Search Path, Xcode is able to recognize the Orientation.h but can't build:

`$(SRCROOT)/../node_modules/react-native-orientation-locker/iOS/RCTOrientation`

Please consider it when you have time 😄 . Thank you for the great library

**Comment by wonday** [comment]
not build error, it is link error, so you should check your lib path...
