### ISSUE TITLE
Can't build for iOS - library not found for -lRCTOrientation-tvOS

### ISSUE THREAD

**Issue by flashman2** [wonday/react-native-orientation-locker#62]
When I try to build app with this library for iOS, get following error:

info ld: library not found for -lRCTOrientation-tvOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening xxx.xcodeproj

** BUILD FAILED **

React Native 0.59.4
xCode 10.2 (Legacy Build System)

Fast workaround: remove libRCTOrientation-tvOS.a from Build Phases -> Link Binary With Libraries.
When only libRCTOrientation.a is added app can be compiled.

Is there any solution to fix this problem permanently so that it will work with tvOS?

**Comment by connect2jc** [comment]
@flashman2  I got the same error.Temporary solution would be go to your scode project and remove the library ( I assume you are not preparing your app for tv os). Check out the attached file.
![lib_not_found](https://user-images.githubusercontent.com/30878723/56376837-31e4ae00-61c6-11e9-9dd8-5ddec2cab06a.png)

**Comment by shubham1164** [comment]
Getting the same error

**Comment by bitlab-code** [comment]
Same error (RN 0.59.9)
workaround from [connect2js](https://github.com/wonday/react-native-orientation-locker/issues/62#issuecomment-484585931) work fine 
@wonday I don't think this is a solved issue but if we need to edit manually with Xcode you should write in README
