### ISSUE TITLE
Question: in iOS lockToPortrait changes orientation but doesn't "lock" it?

### ISSUE THREAD

**Issue by johnckendall** [wonday/react-native-orientation-locker#63]
For iOS:
1. lockToPortrait() is called
2. rotate device to landscape
3. The screen rotates; does not stay in portrait

For Android:
1. lockToPortrait() is called
2. the device stays in portrait; it stays "locked"

Is this difference between the platforms the expected behavior?

Is it possible to actually lock the orientation in iOS as it does in Android?

**Comment by wonday** [comment]
It seems you do not configure well as readme.
Are you add codes to AppDelegate.m?

**Comment by johnckendall** [comment]
Yes, we have added the new method to the AppDelegate.m as shown in the readme and the project is compiling and running.

Also note:  if the device is in landscape _before_ the lockToPortrait() method is called then the screen DOES rotate to portrait.  But if the device is then rotated to portrait and back to landscape then the screen rotates back to landscape.

**Comment by wonday** [comment]
Give me related codes of JS.

**Comment by johnckendall** [comment]
Crud, looks like it's my bad (and misunderstanding of objective-C I guess).
I had changed "application" to "app" in trying to get things to work.

After changing back it is now working.  Unfortunately for me I still don't understand why this makes a difference (or why no compile or runtime error)!  Sorry to bother you with this.

```
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}
```

to:

```
- (UIInterfaceOrientationMask)app:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}
```

**Comment by wonday** [comment]
the above is your new method, the bellow is override method, so no error.

**Comment by johnckendall** [comment]
Ah! Gotcha; still having trouble understanding method signatures and detecting when something is subclassed.  Thanks for the help!

**Comment by GuilhermeSantosmain** [comment]
this works for me in the first time, but after didn't work anymore... any suggestion @wonday?
