### ISSUE TITLE
PSA: Don't Enable Upside Down

### ISSUE THREAD

**Issue by jordangrant** [wonday/react-native-orientation-locker#65]
Please add to the readme - don't enable Upside Down orientation, otherwise none of the functions work such as Orientation.lockToLandscape();

<img width="689" alt="Screen Shot 2019-04-20 at 2 22 13 AM" src="https://user-images.githubusercontent.com/7986493/56453644-77fb5800-6313-11e9-9206-b360fed133cc.png">

**Comment by DanielBoening** [comment]
Thanks! 
For me the first orientation changed call was not fired because of this.

**Comment by jordangrant** [comment]
One more quick comment. When you distribute the app, iPad requires Upside Down if “Requires full screen” is unchecked. So check that to keep upside down disabled.

**Comment by dorthwein** [comment]
just wondering why is iOS upsidedown not supported?  This a TODO or is there a specific reason?

**Comment by winseyli** [comment]
Thanks!! This thread save my life!!!

**Comment by ImHamzaAnwer** [comment]
is there any way to lock to portrait mode for ipad ? if I uncheck upside down distribution throws error that all orientations are required
