### ISSUE TITLE
Can this package be installed without Cocoapods?

### ISSUE THREAD

**Issue by DISKONEKTeD** [wonday/react-native-orientation-locker#69]
Is this package only installed via Cocoapods? or can it be manually installed too? I noticed there is zero instructions for manual installation. I have about a year old project and don't use cocoapods (so i don't want to suddenly introduce it for just one package).

from my understanding this is a fork, would i be able to do it similar to this? https://github.com/yamill/react-native-orientation#manual-linking

**Comment by wonday** [comment]
You can use this to install it
```
npm install react-native-orientation-locker --save
react-native link react-native-orientation-locker
```

or manually install like https://github.com/yamill/react-native-orientation#manual-linking

**Comment by DISKONEKTeD** [comment]
Oh, I misread. Ok thank you.
