### ISSUE TITLE
android Lock landscape, unable to trigger onPress event

### ISSUE THREAD

**Issue by js1121302139** [wonday/react-native-orientation-locker#74]
`
import React, { Component } from 'react';
import { View, Text, StyleSheet,TouchableOpacity } from 'react-native';
import Orientation from 'react-native-orientation-locker';

class HeightLighiDetail extends Component {
    render() {
        return (
            <TouchableOpacity onPress={(e) => {
                Orientation.getOrientation(e => {
                    if (e === 'LANDSCAPE-RIGHT') {
                        Orientation.lockToPortrait()
                    } else {
                        Orientation.lockToLandscape()
                    }

                })
            }} style={{ flex: 1 }}>

            </TouchableOpacity>
        );
    }
}

export default HeightLighiDetail;`

"react": "16.8.3",
    "react-native": "0.59.3",
"react-native-orientation-locker": "^1.1.6",

**Comment by js1121302139** [comment]
@wonday

**Comment by wonday** [comment]
```onPress={(e) ```  and```Orientation.getOrientation(e => ```
the same param ```e```,  no problem?
