### ISSUE TITLE
Why no "lockToPortraitUpsideDown" method?

### ISSUE THREAD

**Issue by davidworkman9** [wonday/react-native-orientation-locker#75]
Curious as to why there's no lock to portrait upside down function? I see an open issue stating there's issues with even enabling the feature, but it looks like that might be specific to iOS.

**Comment by ovidius72** [comment]
I'm also interested in this question because I need to feature on an Android device. Thanks.

**Comment by ovidius72** [comment]
The method is available and working fine. It's not in the typescript type definition files.
