### ISSUE TITLE
orientationDidChange delay 1 step

### ISSUE THREAD

**Issue by truongluong1314520** [wonday/react-native-orientation-locker#78]
Hi @wonday , I just find out there is an interesting issue.

Issue:
====

`orientationDidChange` will be delayed in iPad if we set `upside down` to be true.

For example, we open the app on iPad in "portrait" and rotate it to "landscape", `orientationDidChange` won't fire. Later we rotate it to "portrait", `orientationDidChange` fires and return value "landscapeLeft/landscapeRight"

How to fix it:
=========

Simply disable `upside down` for iPad and everything works like a charm

I create this for people who get the same issue like me. Can you please make a note in README.md

Thank you for the awesome lib 😄

**Comment by wonday** [comment]
I had added it to README

**Comment by msageryd** [comment]
I just migrated my app to RN 0.63 and a new XCode version. XCode wouldn't let me build the app if I wouldn't add support for upside-down. This was due to multitasking support on iPad, according to XCode.
