### ISSUE TITLE
lock to portrait doesnot work on iOS

### ISSUE THREAD

**Issue by Thanmai-C** [wonday/react-native-orientation-locker#8]
Hi,
I am locking the orientation to portrait, in componentDidMount of my screen.
It locks the screen to portrait on android, but doesnt seem to work on iOS.

Snippet:
import Orientation from "react-native-orientation-locker";
componentDidMount() {
		Orientation.lockToPortrait(); // this will lock the view to Portrait
}

**Comment by wonday** [comment]
Do you config it like readme.ME?
It should add the following codes to iOS files,
```
#import "Orientation.h" // <--- import

@implementation AppDelegate

  // ...

  - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    return [Orientation getOrientation];
  }

@end
```

**Comment by takameyer** [comment]
I'm having the same problem.  AppDelegate.m is correctly configured.  I'm receiving the events that the orientation has changed, but it will not lock.  Can you provide an example where locking to portrait mode works?

**Comment by Thanmai-C** [comment]
@wonday @takameyer Any solution to lock to portrait on iOS?

**Comment by takameyer** [comment]
I had to enable „Requires full screen“ in the Target General settings (Deployment info)

**Comment by Thanmai-C** [comment]
But still it doesn't work for me.
@wonday doesn't work on iOS?

**Comment by wonday** [comment]
After install, just call 
```
import Orientation from 'react-native-orientation-locker';
Orientation.lockToPortrait();
```

My App work fine on Android and iOS.

**Comment by DragonSpirit** [comment]
Not work on ipad without "Requires full screen", can I use without this checkbox?

**Comment by ZeroCool00** [comment]
Any solution yet? locktoLandscape also not working in ios. Android is fine

**Comment by wonday** [comment]
I have an example that uses it, you can see the project setting and usage.
[here](https://github.com/wonday/react-native-pdf/tree/master/example)

**Comment by paulxuca** [comment]
@Theng 

I have a fork of this repo which adds functionality to try to fix that: https://github.com/paulxuca/react-native-orientation-locker

Please let me know if that works and I'll open a PR here!

**Comment by wonday** [comment]
@paulxuca 
Your fork seems no problem, can you send a PR to me?

**Comment by paulxuca** [comment]
Cool! Thank you.

**Comment by paulxuca** [comment]
https://github.com/wonday/react-native-orientation-locker/pull/38

**Comment by Theng** [comment]
@paulxuca for me this is still not working, do I need to do something to my code or just change to your repo, this is the app I am working on https://streamable.com/5d72o , 1st I open it in portrait which working as I expected , 2nd I rotate iPhone to landscape then open the app, as you can see in video on the Launch screen it rotate then the component become bigger.

**Comment by matej-cepil** [comment]
@paulxuca Thanks a lot. Now it works as expected.

**Comment by ShantiRanjanDas** [comment]
It is also not working in my case @Theng , I am using your fork. Still not able to lock app in portrait mode, While its gets launched first time.

**Comment by chrismang** [comment]
Try this configuration in AppDelegate.m:

```
#import "Orientation.h" // <--- import

@implementation AppDelegate

  // ...

  - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    while ([[UIDevice currentDevice] isGeneratingDeviceOrientationNotifications]) {
        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];
    }
  
    return [Orientation getOrientation];
  }

@end
```

**Comment by ieroshenko** [comment]
@chrismang your code works for locking, but device orientation listener stops working in my case

**Comment by HaseemUlHaq** [comment]
Make sure you have install Pods
`cd ios && pod install`

Use:
`Orientation.lockToLandscape()`
`Orientation.lockToPortrait()`

**In AppDelegate.m**
write before `@end`

`- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow ``*)window {`
`    while ([[UIDevice currentDevice] isGeneratingDeviceOrientationNotifications]) {`
`        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];`
`    }`
  
`    return [Orientation getOrientation];`
`  }`

**Comment by eramudeep** [comment]
> Make sure you have installed Pods `cd ios && pod install`
> 
> Use: `Orientation.lockToLandscape()` `Orientation.lockToPortrait()`
> 
> **In AppDelegate.m** write before `@end`
> 
> `` - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow ``*)window { `` ` while ([[UIDevice currentDevice] isGeneratingDeviceOrientationNotifications]) {` ` [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];` ` }`
> 
> ` return [Orientation getOrientation];` ` }`

finally got the correct answer. !!! 
Thank you

**Comment by anisurrahman072** [comment]
> Do you config it like readme.ME? You should add the following codes to iOS files,
> 
> ```
> #import "Orientation.h" // <--- import
> 
> @implementation AppDelegate
> 
>   // ...
> 
>   - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
>     return [Orientation getOrientation];
>   }
> 
> @end
> ```

It worked for me 🎉. Thanks you rock @wonday
