### ISSUE TITLE
automatically unlocks orientation after installation? 

### ISSUE THREAD

**Issue by bopeng48** [wonday/react-native-orientation-locker#81]
Hi, thank you for making library. 

Is it possible that after installing this library, it would unlock all device orientation?

My entire app is set to only allow Portrait mode, I was looking into enabling landscape mode on just 1 screen. After installing this package, it seems like it automatically and secretly enabled landscape mode app wide? even though I haven't invoked any functions from this library at all? 

Right now my info.plist has the following settings. 
`	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
`

I did import this library in AppDelegate.m like this 

`#import "../../node_modules/react-native-orientation-locker/iOS/RCTOrientation/Orientation.h"`

But when I rotate my IOS simulator, all my views would go into landscape mode(they would stay in portrait prior to installing this package).

**Comment by bopeng48** [comment]
After looking at it, this is the correct behaviour. However, it is a little confusing to see that your xcode orientation setting being inconsistent with how the app works. Might be a good idea to update the xcode settings when installing the package?

**Comment by vvusts** [comment]
@bopeng48 I am facing same issue. My app is portrait mode only and after installing it all screens are not rotating.
I also wan't to make just one screen to detect screen orientation changes can you share your experience on this please?

**Comment by yemd** [comment]
Exactly the same here, I twisted my head a lot of time before figuring it out, I ended up setting orientation on a per-screen basis, would have been good to at least mention this in the README.
Excellent package nonetheless
