### ISSUE TITLE
After installing module all orientations are allowed?

### ISSUE THREAD

**Issue by vvusts** [wonday/react-native-orientation-locker#85]
My app is locked to portrait mode only.
I installed this module as I need to detect orientation in only one screen.

When I installed module and if I rotate phone whole application is rotating and:
```
<key>UISupportedInterfaceOrientations</key>
<array>
	<string>UIInterfaceOrientationPortrait</string>
</array>
```
Why is this happening?

**Comment by MaxInMoon** [comment]
Same here. Can it be linked to this?

```
+#import "Orientation.h"

@implementation AppDelegate

// ...

+- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
+  return [Orientation getOrientation];
+}

@end
```

**Comment by MaxInMoon** [comment]
related to https://github.com/wonday/react-native-orientation-locker/issues/81
